apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-gateway-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: api-gateway-ca
  secretName: api-gateway-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - api-gateway-service.clean-architecture
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: api-gateway-cluster-issuer  
spec:
  ca:
    secretName: api-gateway-ca
