apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: identity-cluster-issuer
  name: identity-ingress
spec:
  rules:
  - host: identity.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: identity-service
            port:
              number: 80
  tls:
  - hosts:
    - identity.local
    secretName: identity-tls
