apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: identity-ca
  secretName: identity-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - blazorwebassembly.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: identity-cluster-issuer  
spec:
  ca:
    secretName: identity-ca
