apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-deployment
spec:
  template:
    metadata:
      labels:
        app: basket
    spec:
      containers:
      - name: basket
        image: dockerprivateregistry.local/basket:latest
        startupProbe:
          httpGet:
            path: /health/startup
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 80
          successThreshold: 3       
        env:
        {{ range $k, $v := .Values.global.env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
