apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: basket-cluster-issuer
  name: basket-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: basket-service.clean-architecture
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: basket-service
            port:
              number: 80
  tls:
  - hosts:
    - basket-service.clean-architecture
    secretName: basket-tls
