apiVersion: v1
kind: Service
metadata:
  name: basket-service
  labels:
    app: basket
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP  
  selector:
    app: basket
