apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: order-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: order-ca
  secretName: order-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - blazorwebassembly.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: order-cluster-issuer  
spec:
  ca:
    secretName: order-ca
