apiVersion: batch/v1
kind: Job
metadata:
  name: order-database-migration-job
  labels:
    app: order
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: "dockerprivateregistry.local/order:latest"
        imagePullPolicy: IfNotPresent
        command: ["dotnet"]
        args: ["CleanArchitecture.Services.Order.API.dll", "migrate-database"]
        env:
          {{- $env := merge .Values.env .Values.global.env -}}
          {{ range $k, $v := $env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
      restartPolicy: Never
