apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-webassembly-deployment
  labels:
    app: blazor-webassembly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-webassembly
  template:
    metadata:
      labels:
        app: blazor-webassembly
    spec:
      containers:
      - name: blazor-webassembly
        image: dockerprivateregistry.local/blazorwebassembly:latest
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /health/startup
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 80
          successThreshold: 3       
        env:
        {{ range $k, $v := .Values.global.env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
