apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: blazor-webassembly-cluster-issuer
  name: blazor-webassembly-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: blazor-webassembly-service.clean-architecture
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: blazor-webassembly-service
            port:
              number: 80
  tls:
  - hosts:
    - blazor-webassembly-service.clean-architecture
    secretName: blazor-webassembly-tls
