apiVersion: batch/v1
kind: Job
metadata:
  name: order-database-migration-job
  labels:
    app: order
spec:
  backoffLimit: 1
  template:    
    spec:
      containers:
      - name: order-database-migration
        image: "dockerprivateregistry.local/order:latest"
        imagePullPolicy: Always
        command: ["dotnet"]
        args: ["CleanArchitecture.Services.Order.API.dll", "migrate-database"]
        env:
        {{ range $k, $v := .Values.global.env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
      restartPolicy: Never
