apiVersion: batch/v1
kind: Job
metadata:
  name: payment-database-migration-job
  labels:
    app: payment
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: "dockerprivateregistry.local/payment:latest"
        imagePullPolicy: IfNotPresent
        command: ["dotnet"]
        args: ["CleanArchitecture.Services.Payment.API.dll", "migrate-database"]
        env:
          {{- $env := merge .Values.env .Values.global.env -}}
          {{ range $k, $v := $env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
      restartPolicy: Never
