apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: catalog-cluster-issuer
  name: catalog-ingress
spec:
  rules:
  - host: catalog.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: catalog-service
            port:
              number: 80
  tls:
  - hosts:
    - catalog.local
    secretName: catalog-tls
