apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      initContainers:
      - name: "catalog-database-migration-init"
        image: "groundnuty/k8s-wait-for:1.3"
        imagePullPolicy: IfNotPresent
        args: 
        - "job"
        - "catalog-database-migration-job"     
      containers:
      - name: catalog
        image: dockerprivateregistry.local/catalog:latest
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /health/startup
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 80
          successThreshold: 3       
        env:
        {{ range $k, $v := .Values.global.env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
