apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: catalog-cluster-issuer
  name: catalog-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: catalog-service.clean-architecture
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: catalog-service
            port:
              number: 80
  tls:
  - hosts:
    - catalog-service.clean-architecture
    secretName: catalog-tls
