apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-database-migration-job
  labels:
    app: catalog
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: "dockerprivateregistry.local/catalog:latest"
        imagePullPolicy: Always
        command: ["dotnet"]
        args: ["CleanArchitecture.Services.Catalog.API.dll", "migrate-database"]
        env:
        {{ range $k, $v := .Values.global.env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
      restartPolicy: Never
